dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.6"

before_install:
  - sudo apt-get install -y python3-pykcs11 python3-cryptography python3-openssl python3-lxml

# command to install dependencies
install:
  - python3 setup.py -q install

# command to run tests
script:
  - python3 setup.py test
